import type {
  AdminDoctorStatus,
  Appointment,
  CalendarEvent,
  Doctor,
  Specialty,
  Stat,
} from "@/lib/types";

export const specialties: Specialty[] = [
  "Cardiology",
  "Dermatology",
  "Neurology",
  "Pediatrics",
  "Orthopedics",
];

export const doctors: Doctor[] = [
  {
    id: 1,
    slug: "maya-santoso",
    name: "Dr. Maya Santoso",
    specialty: "Cardiology",
    location: "Central Jakarta",
    rating: 4.9,
    reviews: 128,
    experience: "12 years",
    nextAvailable: "Today, 14:30",
    languages: ["English", "Bahasa Indonesia"],
    bio: "Specialises in preventive cardiology and hypertension management with a calm, educational bedside manner.",
    credentials: ["MD, Universitas Indonesia", "Fellowship in Preventive Cardiology"],
    highlights: ["Same-day consultation", "ECG review", "Heart health plans"],
    slots: ["09:00", "11:30", "14:30", "16:15"],
  },
  {
    id: 2,
    slug: "rafael-wibowo",
    name: "Dr. Rafael Wibowo",
    specialty: "Dermatology",
    location: "South Jakarta",
    rating: 4.8,
    reviews: 94,
    experience: "9 years",
    nextAvailable: "Tomorrow, 10:15",
    languages: ["English", "Bahasa Indonesia", "Mandarin"],
    bio: "Focuses on acne treatment, eczema care, and cosmetic dermatology with evidence-based plans.",
    credentials: ["MD, Airlangga University", "Board Certified Dermatologist"],
    highlights: ["Teleconsult friendly", "Skin imaging", "Teen acne clinic"],
    slots: ["10:15", "13:00", "15:45"],
  },
  {
    id: 3,
    slug: "nina-pramesti",
    name: "Dr. Nina Pramesti",
    specialty: "Pediatrics",
    location: "West Jakarta",
    rating: 5,
    reviews: 176,
    experience: "15 years",
    nextAvailable: "Today, 18:00",
    languages: ["English", "Bahasa Indonesia"],
    bio: "Known for family-centered care, vaccination planning, and child development follow-ups.",
    credentials: ["MD, Gadjah Mada University", "Pediatric Care Certification"],
    highlights: ["Evening slots", "Vaccination plans", "Growth monitoring"],
    slots: ["08:30", "12:00", "18:00"],
  },
  {
    id: 4,
    slug: "adrian-kurnia",
    name: "Dr. Adrian Kurnia",
    specialty: "Orthopedics",
    location: "North Jakarta",
    rating: 4.7,
    reviews: 72,
    experience: "11 years",
    nextAvailable: "Friday, 09:30",
    languages: ["English", "Bahasa Indonesia"],
    bio: "Treats sports injuries, joint pain, and post-operative recovery with clear rehabilitation plans.",
    credentials: ["MD, Padjadjaran University", "Sports Medicine Fellowship"],
    highlights: ["Sports injury focus", "X-ray review", "Rehab planning"],
    slots: ["09:30", "11:00", "13:30", "17:15"],
  },
];

export const patientAppointments: Appointment[] = [
  {
    id: "MB-2049",
    doctor: "Dr. Maya Santoso",
    specialty: "Cardiology",
    date: "18 Apr 2026",
    time: "14:30",
    status: "Upcoming",
    location: "Central Jakarta",
  },
  {
    id: "MB-1927",
    doctor: "Dr. Nina Pramesti",
    specialty: "Pediatrics",
    date: "04 Apr 2026",
    time: "18:00",
    status: "Completed",
    location: "West Jakarta",
  },
  {
    id: "MB-1884",
    doctor: "Dr. Rafael Wibowo",
    specialty: "Dermatology",
    date: "22 Apr 2026",
    time: "10:15",
    status: "Needs action",
    location: "South Jakarta",
  },
];

export const adminStats: Stat[] = [
  {
    label: "Appointments today",
    value: "148",
    caption: "18% higher than last Friday",
  },
  {
    label: "Doctors on duty",
    value: "24",
    caption: "Across 5 specialties",
  },
  {
    label: "Average booking time",
    value: "46s",
    caption: "From search to confirmation",
  },
];

export const doctorRoster: AdminDoctorStatus[] = [
  { name: "Dr. Maya Santoso", fillRate: "92%", status: "Available" },
  { name: "Dr. Nina Pramesti", fillRate: "88%", status: "Fully booked" },
  { name: "Dr. Adrian Kurnia", fillRate: "67%", status: "Available" },
  { name: "Dr. Rafael Wibowo", fillRate: "74%", status: "Needs slot review" },
];

export const adminWeekDays = [
  { key: "Mon", label: "Mon 20" },
  { key: "Tue", label: "Tue 21" },
  { key: "Wed", label: "Wed 22" },
  { key: "Thu", label: "Thu 23" },
  { key: "Fri", label: "Fri 24" },
];

export const adminCalendarEvents: CalendarEvent[] = [
  {
    id: "evt-01",
    doctor: "Dr. Maya Santoso",
    patient: "Sarah Lim",
    specialty: "Cardiology",
    day: "Mon",
    start: "09:00",
    end: "10:00",
    room: "Room A1",
    visitType: "Heart check-up",
    status: "Confirmed",
    notes: "Requested ECG review before consultation.",
    tone: "forest",
  },
  {
    id: "evt-02",
    doctor: "Dr. Nina Pramesti",
    patient: "Lucas Hart",
    specialty: "Pediatrics",
    day: "Mon",
    start: "11:30",
    end: "12:30",
    room: "Room C2",
    visitType: "Vaccination visit",
    status: "Checked in",
    notes: "Bring previous immunization record.",
    tone: "lime",
  },
  {
    id: "evt-03",
    doctor: "Dr. Rafael Wibowo",
    patient: "Mina Putri",
    specialty: "Dermatology",
    day: "Tue",
    start: "10:00",
    end: "11:00",
    room: "Room B3",
    visitType: "Acne follow-up",
    status: "Confirmed",
    notes: "Photo comparison scheduled during visit.",
    tone: "sage",
  },
  {
    id: "evt-04",
    doctor: "Dr. Adrian Kurnia",
    patient: "Daniel Ross",
    specialty: "Orthopedics",
    day: "Tue",
    start: "14:00",
    end: "15:30",
    room: "Room D1",
    visitType: "Knee pain assessment",
    status: "Needs follow-up",
    notes: "MRI results pending at reception desk.",
    tone: "gold",
  },
  {
    id: "evt-05",
    doctor: "Dr. Maya Santoso",
    patient: "Ava Chen",
    specialty: "Cardiology",
    day: "Wed",
    start: "13:00",
    end: "14:30",
    room: "Room A1",
    visitType: "Blood pressure review",
    status: "Confirmed",
    notes: "Patient asked for prescription refill discussion.",
    tone: "forest",
  },
  {
    id: "evt-06",
    doctor: "Dr. Nina Pramesti",
    patient: "Noah Prasetyo",
    specialty: "Pediatrics",
    day: "Wed",
    start: "16:00",
    end: "17:00",
    room: "Room C2",
    visitType: "Growth monitoring",
    status: "Checked in",
    notes: "Parent requested nutrition chart summary.",
    tone: "lime",
  },
  {
    id: "evt-07",
    doctor: "Dr. Rafael Wibowo",
    patient: "Sofi Malik",
    specialty: "Dermatology",
    day: "Thu",
    start: "09:30",
    end: "10:30",
    room: "Room B3",
    visitType: "Skin irritation consult",
    status: "Confirmed",
    notes: "Patch test recommendations already prepared.",
    tone: "sage",
  },
  {
    id: "evt-08",
    doctor: "Dr. Adrian Kurnia",
    patient: "Liam Aditya",
    specialty: "Orthopedics",
    day: "Thu",
    start: "13:30",
    end: "15:00",
    room: "Room D1",
    visitType: "Post-op review",
    status: "Needs follow-up",
    notes: "Physiotherapy handoff planned after appointment.",
    tone: "gold",
  },
  {
    id: "evt-09",
    doctor: "Dr. Maya Santoso",
    patient: "Emma Wijaya",
    specialty: "Cardiology",
    day: "Fri",
    start: "08:30",
    end: "09:30",
    room: "Room A2",
    visitType: "Chest pain screening",
    status: "Confirmed",
    notes: "Front desk flagged insurance verification complete.",
    tone: "forest",
  },
  {
    id: "evt-10",
    doctor: "Dr. Rafael Wibowo",
    patient: "Kai Ibrahim",
    specialty: "Dermatology",
    day: "Fri",
    start: "15:00",
    end: "16:00",
    room: "Room B3",
    visitType: "Dermatitis review",
    status: "Checked in",
    notes: "Patient requested translated aftercare instructions.",
    tone: "sage",
  },
];

export const adminCredentials = {
  email: "admin@medibook.dev",
  password: "Admin123!",
};
